### ISSUE TITLE
rtl433 battery status is not properly handled

### ISSUE THREAD

**Issue by Gonioul** [pbkhrv/rtl_433-hass-addons#86] opened 2022-04-20 23:18 UTC
Batteries shows as 100% without icon
Wheareas other integrations shows battery icon

**Comment by Gonioul** [comment] 2022-04-20 23:25
![image](https://user-images.githubusercontent.com/64291573/164340655-ebc84efb-23ae-4767-9193-bf3a2b702c36.png)

**Comment by Gonioul** [comment] 2022-04-20 23:25
![image](https://user-images.githubusercontent.com/64291573/164340718-e5dab574-670e-42b5-9552-2a24f9caa19c.png)

**Comment by Gonioul** [comment] 2022-04-20 23:27
![image](https://user-images.githubusercontent.com/64291573/164340820-9157298a-6615-449f-a247-e99257e869d6.png)

**Comment by Gonioul** [comment] 2022-04-24 19:44
Looks like it should be an integer

**Comment by deviantintegral** [comment] 2022-04-25 15:48
Thanks for the report. Are you thinking the problem is with the `value_template` line at https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_mqtt_hass.py#L162-L173 ?

**Comment by Gonioul** [comment] 2022-04-26 18:14
I have no idea... But converting the level to an integer seems logical if it's a 0-100 range.

**Comment by Gonioul** [comment] 2022-05-03 17:56
Another difference, the same sensor with rfxcom (top) and rtl_433 (below).
It didn't rename the rtl_433 entities for now, so it's the default name.

![image](https://user-images.githubusercontent.com/64291573/166511745-027ea790-b750-4596-8465-8981a78436b7.png)

![image](https://user-images.githubusercontent.com/64291573/166511379-0c58d79a-c5da-4765-9470-7135d761ab21.png)

**Comment by Gonioul** [comment] 2022-05-03 18:27
EnCh - Entity Checker for AppDaemon doesn't seem to recognize the low battery level with rtl_433, works with rfxtrx, dunno why, no trace in logs. Maybe the float value again.

**Comment by deviantintegral** [comment] 2022-05-09 18:24
I think it would be good if we could confirm if Home Assistant is expecting ints or floats for battery percentages. I haven't found docs or code yet confirming one way or another.

**Comment by jaseelye** [comment] 2022-05-24 22:29
This is what I use and it works great.
"value_template": "{% if is_number(value) %}{% set temp_val = float(value) * 100 | float(default=0) %}{{ temp_val | float(default=0) | round(0) }}{% endif %}"

**Comment by deviantintegral** [comment] 2024-02-17 00:50
Since this is from the upstream code, and I don't have any devices that expose this battery info to test, I'm closing this out. Please feel free to open a new issue if a PR is filed upstream we should patch in to improve this. Thanks!

**Closed by deviantintegral** 2024-02-17 00:50 UTC
Labels: needs fix upstream
