### ISSUE TITLE
rtl_433 MQTT Auto Discovery will not run after update

### ISSUE THREAD

**Issue by slandroe** [pbkhrv/rtl_433-hass-addons#179] opened 2024-02-17 10:12 UTC
### The problem

Auto discovery addon crashes after rtl_433 and rtl_433 autodiscovery version update yesterday. The day before, I tried the two similar *next addons - with the same behaviour. 

### What addon are you reporting the bug for?

rtl_433_mqtt_autodiscover

### What is the addon version?

0.8.0

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

### Addon log messages

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
mqtt found in this Home Assistance instance.
Starting rtl_433_mqtt_hass.py...
[2024-02-17T09:10:15+0100] INFO:root:Enabling debug logging
[2024-02-17T09:10:15+0100] INFO:root:Discovering all devices
Exception ignored in: <function Client.__del__ at 0x7f28349f8900>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
           ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "/rtl_433_mqtt_hass.py", line 990, in <module>
    run()
  File "/rtl_433_mqtt_hass.py", line 917, in run
    rtl_433_bridge()
  File "/rtl_433_mqtt_hass.py", line 888, in rtl_433_bridge
    mqttc = mqtt.Client()
            ^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by tomgit33** [comment] 2024-02-17 11:25
confirmed, same here. Update rtl_433 an this addon.

**Comment by Magicpulse** [comment] 2024-02-17 13:10
Same here after updating the addon

**Comment by eduardkirkosa** [comment] 2024-02-17 16:51
same here
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
mqtt found in this Home Assistance instance.
Starting rtl_433_mqtt_hass.py...
[2024-02-17T09:10:15+0100] INFO:root:Enabling debug logging
[2024-02-17T09:10:15+0100] INFO:root:Discovering all devices
Exception ignored in: <function Client.__del__ at 0x7f28349f8900>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
           ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "/rtl_433_mqtt_hass.py", line 990, in <module>
    run()
  File "/rtl_433_mqtt_hass.py", line 917, in run
    rtl_433_bridge()
  File "/rtl_433_mqtt_hass.py", line 888, in rtl_433_bridge
    mqttc = mqtt.Client()
            ^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by Skotniki17** [comment] 2024-02-17 17:25
Same here after updating the addon

**Comment by hindsight2021** [comment] 2024-02-17 18:28
Same error post-update as well.

**Comment by deviantintegral** [comment] 2024-02-17 18:54
Thanks for the reports, looks like paho-mqtt released a new major version last week. PR is up at https://github.com/pbkhrv/rtl_433-hass-addons/pull/180.

Closing as a duplicate of https://github.com/pbkhrv/rtl_433-hass-addons/issues/178.

**Closed by deviantintegral** 2024-02-17 18:54 UTC
